spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/proxio}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:proxio}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:proxio}}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
